name: Granchisel
main: us.zingalicio.granchisel.Granchisel
version: ${project.version}
description: ${project.description}
author: zingten11
depend: [Cordstone, PowerNBT, ProtocolLib]
database: true
commands:
  refreshleads:
    aliases: [refreshleashes, rleads]
